### ISSUE TITLE
Self-hosted MacOS Runner with "[error]Unable to resolve actions. Repositories not found : "

### ISSUE THREAD

**Issue by vhsantos26** [actions/runner#1796]
**Describe the bug**
The self-hosted macOS runner (set on AWS EC2 with a Dedicated host) started failing when the setup tries to download the actions. Here are the actions from the last successful execution.

> Download action repository 'actions/checkout@v3' (SHA:a12a3943b4bdde767164f792f33f40b04645d846)
Download action repository 'actions/setup-node@v3' (SHA:9ced9a43a[24](https://github.com/ALJAZEERAPLUS/ump/runs/5757219593?check_suite_focus=true#step:1:24)4f3ac94f13bfd896db8c8f30da67a)
Download action repository 'actions/cache@v3' (SHA:136d96b4aee02b1f0de3ba493b1d47135042d9c0)
Download action repository 'actions/cache@v2' (SHA:937d24475381cd9c75ae6db12cb4e79714b9[26](https://github.com/ALJAZEERAPLUS/ump/runs/5757219593?check_suite_focus=true#step:1:26)ed)
Download action repository 'actions/upload-artifact@v2' (SHA:82c141cc518b40d92cc801eee768e7aafc9c2fa2)

**To Reproduce**
1. Setup self-hosted macOS runner with AWS EC2
2. Setup job using one of the actions mentioned above
3. Run the workflow

**Expected behavior**
The workflow must be executed successfully

## Runner Version and Platform
2.289.1

OS of the machine running the runner? 
- System Version: macOS 12.2.1 (21D62)
- Kernel Version: Darwin 21.3.0

## What's not working?
Unable to download the actions

### Set up job
```2022-03-30T16:42:42.7760465Z Requested labels: self-hosted, macos, ump-mobile
2022-03-30T16:42:42.7760571Z Job defined at: ******.github/workflows/main.yml@refs/pull/605/merge
2022-03-30T16:42:42.7760597Z Waiting for a runner to pick up this job...
2022-03-30T16:42:43.6482873Z Job is about to start running on the runner: ****** (organization)
2022-03-30T16:42:42.7914570Z Current runner version: '2.289.1'
2022-03-30T16:42:42.7920020Z Runner name: '******'
2022-03-30T16:42:42.7920440Z Runner group name: '******'
2022-03-30T16:42:42.7921020Z Machine name: '******'
2022-03-30T16:42:42.7923130Z ##[group]GITHUB_TOKEN Permissions
2022-03-30T16:42:42.7923660Z Actions: write
2022-03-30T16:42:42.7924000Z Checks: write
2022-03-30T16:42:42.7924250Z Contents: write
2022-03-30T16:42:42.7924510Z Deployments: write
2022-03-30T16:42:42.7924770Z Discussions: write
2022-03-30T16:42:42.7925060Z Issues: write
2022-03-30T16:42:42.7925310Z Metadata: read
2022-03-30T16:42:42.7925570Z Packages: write
2022-03-30T16:42:42.7925820Z Pages: write
2022-03-30T16:42:42.7926110Z PullRequests: write
2022-03-30T16:42:42.7926400Z RepositoryProjects: write
2022-03-30T16:42:42.7926700Z SecurityEvents: write
2022-03-30T16:42:42.7926960Z Statuses: write
2022-03-30T16:42:42.7927240Z ##[endgroup]
2022-03-30T16:42:42.7929930Z Secret source: Actions
2022-03-30T16:42:42.7930400Z Prepare workflow directory
2022-03-30T16:42:42.8610860Z Prepare all required actions
2022-03-30T16:42:42.8750740Z Getting action download info
2022-03-30T16:42:43.2577550Z ##[error]Unable to resolve actions. Repositories not found : 
```

## Runner and Worker's Diagnostic Logs
```
[2022-03-30 20:03:28Z INFO HostContext] Well known directory 'Actions': '/Users/ec2-user/actions-runner/_work/_actions'
[2022-03-30 20:03:28Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'd5fd56bb-6bca-4bfb-b9b7-00118dd711e2', success rate: 1/1.
[2022-03-30 20:03:29Z ERR  GitHubActionsService] POST request to https://pipelines.actions.githubusercontent.com/hRwW8DcdCvv5281xUTA4Yy0g9HqJoJGMgrq1bg6NA4JP8oanUa/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/2673a369-9095-448b-8d9c-ea794c830ec6/actiondownloadinfo?jobId=18ee2e56-ffd5-5b64-801c-7f58e91643cd failed. HTTP Status: UnprocessableEntity, AFD Ref: Ref A: C0D5A4E04E52414E9431E590A19A1355 Ref B: DB3EDGE2214 Ref C: 2022-03-30T20:03:28Z
[2022-03-30 20:03:29Z ERR  JobExtension] Caught exception from JobExtension Initialization: GitHub.DistributedTask.WebApi.UnresolvableActionDownloadInfoException: Unable to resolve actions. Repositories not found : 
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Worker.ActionManager.GetDownloadInfoAsync(IExecutionContext executionContext, List`1 actions)
   at GitHub.Runner.Worker.ActionManager.GetDownloadInfoAsync(IExecutionContext executionContext, List`1 actions)
   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
[2022-03-30 20:03:29Z INFO ExecutionContext] Publish step telemetry for current step {
  "action": "setup_job",
  "type": "runner",
  "stage": "Pre",
  "stepId": "d5fd56bb-6bca-4bfb-b9b7-00118dd711e2",
  "result": "failed",
  "errorMessages": [
    "Unable to resolve actions. Repositories not found : "
  ],
  "executionTimeInSeconds": 1
}.
[2022-03-30 20:03:29Z ERR  JobRunner] Job initialize failed.
[2022-03-30 20:03:29Z ERR  JobRunner] Caught exception from InitializeJob: GitHub.DistributedTask.WebApi.UnresolvableActionDownloadInfoException: Unable to resolve actions. Repositories not found : 
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Worker.ActionManager.GetDownloadInfoAsync(IExecutionContext executionContext, List`1 actions)
   at GitHub.Runner.Worker.ActionManager.GetDownloadInfoAsync(IExecutionContext executionContext, List`1 actions)
   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
[2022-03-30 20:03:29Z INFO JobRunner] Shutting down the job server queue.
[2022-03-30 20:03:29Z INFO JobServerQueue] Fire signal to shutdown all queues.
[2022-03-30 20:03:29Z INFO JobServerQueue] Job timeline record has been updated for the first time.
[2022-03-30 20:03:29Z INFO JobServerQueue] All queue process task stopped.
[2022-03-30 20:03:29Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'd5fd56bb-6bca-4bfb-b9b7-00118dd711e2', success rate: 1/1.
[2022-03-30 20:03:29Z INFO JobServerQueue] Web console line queue drained.
[2022-03-30 20:03:29Z INFO JobServerQueue] Uploading 2 files in one shot.
[2022-03-30 20:03:30Z INFO JobServerQueue] Try to upload 2 log files or attachments, success rate: 2/2.
[2022-03-30 20:03:30Z INFO JobServerQueue] File upload queue drained.
[2022-03-30 20:03:30Z INFO JobServerQueue] Timeline update queue drained.
[2022-03-30 20:03:30Z INFO JobServerQueue] Disposing job server ...
[2022-03-30 20:03:30Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2022-03-30 20:03:30Z INFO TempDirectoryManager] Cleaning runner temp folder: /Users/ec2-user/actions-runner/_work/_temp
[2022-03-30 20:03:30Z INFO HostContext] Well known directory 'Bin': '/Users/ec2-user/actions-runner/bin.2.289.1'
[2022-03-30 20:03:30Z INFO HostContext] Well known directory 'Root': '/Users/ec2-user/actions-runner'
[2022-03-30 20:03:30Z INFO HostContext] Well known directory 'Diag': '/Users/ec2-user/actions-runner/_diag'
[2022-03-30 20:03:30Z INFO HostContext] Well known config file 'Telemetry': '/Users/ec2-user/actions-runner/_diag/.telemetry'
[2022-03-30 20:03:30Z INFO JobRunner] Raising job completed event
[2022-03-30 20:03:30Z INFO Worker] Job completed.
```

**Comment by SudoSpartanDan** [comment]
Experiencing this as well on a Linux Self-Hosted Runner.

**Comment by TingluoHuang** [comment]
We are looking, sorry for the issue.

**Comment by SudoSpartanDan** [comment]
If it helps, I tried with the `288.1` runner version and experienced the same error.

**Comment by TingluoHuang** [comment]
It's a server-side bug, we are working on revert.

**Comment by TingluoHuang** [comment]
The change has been reverted, this should be solved now. Sorry for the disruptions. 😭

**Comment by vhsantos26** [comment]
Thanks a lot @TingluoHuang it solved the problem

**Comment by rawis** [comment]
Still experiencing this as well on a Linux Self-Hosted Runner, 

Github Enterprise Server 3.5.3 (default using Current runner version: '2.289.3' on GHES),

OS: Ubuntu 20.04
