### ISSUE TITLE
github.action_path contains wrong path when used inside a container

### ISSUE THREAD

**Issue by WIStudent** [actions/runner#2185]
**Describe the bug**
When using `${{ github.action_path }}` inside a local composite action and calling this action in a job that runs inside a container, `${{ github.action_path }}` gets resolved to `/home/runner/work/ga-test-public/ga-test-public/./.github/actions/repro` instead of `/__w/ga-test-public/ga-test-public/./.github/actions/repro`.

There are other closed issues describing the same problem (https://github.com/actions/runner/issues/716, https://github.com/actions/runner/issues/965) and a merged pull request (https://github.com/actions/runner/pull/1762) that should have fixed the issue, but I am still getting the wrong path on GitHub shared runners with version 2.297.0

**To Reproduce**
Here is a [reproduction repo](https://github.com/WIStudent/ga-test-public) and a [workflow run](https://github.com/WIStudent/ga-test-public/actions/runs/3197544889/jobs/5220901026) with the mentioned issue.

```yml
# .github/workflow/test.yml
name: Reploduce the bug

on: 
  push: {}
  workflow_dispatch: {}

jobs:
  bug-in-container:
    runs-on: ubuntu-20.04
    container:
      image: centos:7
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/repro

      - run: echo runner.temp = ${{ runner.temp }}
      - run: ls -al ${{ runner.temp }} || true

      - run: echo runner.tool_cache = ${{ runner.tool_cache }}
      - run: ls -al ${{ runner.tool_cache }} || true
```
```yml
# .github/actions/repo/action.yml
name: 'Reproduce the bug'
description: ''
inputs: {}
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo github.action_path: ${{ github.action_path }}
        ls -al ${{ github.action_path }} || true
```

**Expected behavior**
`${{ github.action_path }}` should be resolved to a path inside the container, not to a path on the host machine.

## Runner Version and Platform
GitHub shared runner version 2.297.0

## What's not working?
![grafik](https://user-images.githubusercontent.com/2707930/194333103-96b613b3-a1c9-45b0-a04e-05814fd52215.png)

**Comment by abhijeetdhoke** [comment]
> 
What is end result in .yml file how to implement this change to .yml file

**Comment by MSAdministrator** [comment]
Has there been any updates to this issue? This is blocking some internal workflows.

**Comment by nikola-jokic** [comment]
Hey @MSAdministrator,

This [PR](https://github.com/actions/runner/pull/2517) is in review and as soon as it is in, and the feature flag is on, then it should be okay.
Until then, can you try passing actions_path as an env. Env variables are translated so container paths so it should be okay if you can use it :relaxed:

**Comment by nikola-jokic** [comment]
We merged the PR so the next release should have this functionality :relaxed: . We also have a feature flag in case something goes wrong

**Comment by BitProcessor** [comment]
For anyone struggling with this:

Let's say you created a custom action with a script, with the script called `run.sh` and residing in the root of the action.

```
runs:
  using: composite
  steps:
    - name: Run script
      shell: bash
      run: ${GITHUB_ACTION_PATH}/run.sh
```

That will get it to work if you are running your build inside a container.

**Comment by nicola-lunghi** [comment]
This issue is still present on latest runner.
See my test workflow here:
- https://github.com/nicola-lunghi/test-container-env/actions/runs/6432167437/job/17466455083

```
2023-10-06T13:18:02.8361541Z Requested labels: ubuntu-latest
2023-10-06T13:18:02.8361816Z Job defined at: nicola-lunghi/test-container-env/.github/workflows/test_container_envs.yml@refs/heads/main
2023-10-06T13:18:02.8361970Z Waiting for a runner to pick up this job...
2023-10-06T13:18:03.4555671Z Job is waiting for a hosted runner to come online.
2023-10-06T13:18:05.9740941Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
2023-10-06T13:18:08.1307811Z Current runner version: '2.309.0'
2023-10-06T13:18:08.1334928Z ##[group]Operating System
2023-10-06T13:18:08.1335512Z Ubuntu
2023-10-06T13:18:08.1335850Z 22.04.3
2023-10-06T13:18:08.1336250Z LTS
2023-10-06T13:18:08.1336575Z ##[endgroup]
2023-10-06T13:18:08.1336924Z ##[group]Runner Image
2023-10-06T13:18:08.1337264Z Image: ubuntu-22.04
2023-10-06T13:18:08.1337621Z Version: 20231001.1.0
2023-10-06T13:18:08.1338239Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231001.1/images/linux/Ubuntu2204-Readme.md
2023-10-06T13:18:08.1338928Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231001.1
2023-10-06T13:18:08.1339362Z ##[endgroup]
2023-10-06T13:18:08.1339748Z ##[group]Runner Image Provisioner
2023-10-06T13:18:08.1340194Z 2.0.310.1
2023-10-06T13:18:08.1340462Z ##[endgroup]
2023-10-06T13:18:08.1341196Z ##[group]GITHUB_TOKEN Permissions
2023-10-06T13:18:08.1342841Z Contents: read
2023-10-06T13:18:08.1343331Z Metadata: read
2023-10-06T13:18:08.1343910Z Packages: read
2023-10-06T13:18:08.1344321Z ##[endgroup]
2023-10-06T13:18:08.1347986Z Secret source: Actions
2023-10-06T13:18:08.1348533Z Prepare workflow directory
2023-10-06T13:18:08.2389225Z Prepare all required actions
2023-10-06T13:18:08.2580939Z Getting action download info
2023-10-06T13:18:08.5135389Z Download action repository 'actions/upload-artifact@v3' (SHA:a8a3f3ad30e3422c9c7b888a15615d19a852ae32)
2023-10-06T13:18:08.9693569Z Complete job name: run-tests
2023-10-06T13:18:09.0564241Z ##[group]Checking docker version
2023-10-06T13:18:09.0582276Z ##[command]/usr/bin/docker version --format '{{.Server.APIVersion}}'
2023-10-06T13:18:09.1759163Z '1.43'
2023-10-06T13:18:09.1775431Z Docker daemon API version: '1.43'
2023-10-06T13:18:09.1775957Z ##[command]/usr/bin/docker version --format '{{.Client.APIVersion}}'
2023-10-06T13:18:09.2083392Z '1.43'
2023-10-06T13:18:09.2097998Z Docker client API version: '1.43'
2023-10-06T13:18:09.2104961Z ##[endgroup]
2023-10-06T13:18:09.2108421Z ##[group]Clean up resources from previous jobs
2023-10-06T13:18:09.2115456Z ##[command]/usr/bin/docker ps --all --quiet --no-trunc --filter "label=94351b"
2023-10-06T13:18:09.2317951Z ##[command]/usr/bin/docker network prune --force --filter "label=94351b"
2023-10-06T13:18:09.2489359Z ##[endgroup]
2023-10-06T13:18:09.2490485Z ##[group]Create local container network
2023-10-06T13:18:09.2502596Z ##[command]/usr/bin/docker network create --label 94351b github_network_a5f2de3aaa54493088ab51da83b24320
2023-10-06T13:18:09.3280429Z f87142ff6ec8f1b84c683845320ca2173a36a629da0c6eb7a812104990b31fe9
2023-10-06T13:18:09.3302367Z ##[endgroup]
2023-10-06T13:18:09.3399681Z ##[group]Starting job container
2023-10-06T13:18:09.3422273Z ##[command]/usr/bin/docker pull ubuntu:20.04
2023-10-06T13:18:09.6322157Z 20.04: Pulling from library/ubuntu
2023-10-06T13:18:09.6337323Z Digest: sha256:33a5cc25d22c45900796a1aca487ad7a7cb09f09ea00b779e3b2026b4fc2faba
2023-10-06T13:18:09.6337788Z Status: Image is up to date for ubuntu:20.04
2023-10-06T13:18:09.6338074Z docker.io/library/ubuntu:20.04
2023-10-06T13:18:09.6474009Z ##[command]/usr/bin/docker create --name 01832559a3e347b59e23a7f57fca9b63_ubuntu2004_cff52c --label 94351b --workdir /__w/test-container-env/test-container-env --network github_network_a5f2de3aaa54493088ab51da83b24320 -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.309.0/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" ubuntu:20.04 "-f" "/dev/null"
2023-10-06T13:18:09.7102703Z 82749e3b34d9c93658fe36c820b84f422e43b5161cfcc607cd69949eab3c0fe6
2023-10-06T13:18:09.7117640Z ##[command]/usr/bin/docker start 82749e3b34d9c93658fe36c820b84f422e43b5161cfcc607cd69949eab3c0fe6
2023-10-06T13:18:10.0820344Z 82749e3b34d9c93658fe36c820b84f422e43b5161cfcc607cd69949eab3c0fe6
2023-10-06T13:18:10.0830910Z ##[command]/usr/bin/docker ps --all --filter id=82749e3b34d9c93658fe36c820b84f422e43b5161cfcc607cd69949eab3c0fe6 --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
2023-10-06T13:18:10.0986452Z 82749e3b34d9c93658fe36c820b84f422e43b5161cfcc607cd69949eab3c0fe6 Up Less than a second
2023-10-06T13:18:10.1004414Z ##[command]/usr/bin/docker inspect --format "{{range .Config.Env}}{{println .}}{{end}}" 82749e3b34d9c93658fe36c820b84f422e43b5161cfcc607cd69949eab3c0fe6
2023-10-06T13:18:10.1178608Z HOME=/github/home
2023-10-06T13:18:10.1184486Z GITHUB_ACTIONS=true
2023-10-06T13:18:10.1185311Z CI=true
2023-10-06T13:18:10.1186095Z PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2023-10-06T13:18:10.1199992Z ##[endgroup]
2023-10-06T13:18:10.1234359Z ##[group]Waiting for all services to be ready
2023-10-06T13:18:10.1236246Z ##[endgroup]
2023-10-06T13:18:10.1675017Z ##[group]Run echo "github.workspace=/home/runner/work/test-container-env/test-container-env"
2023-10-06T13:18:10.1675667Z echo "github.workspace=/home/runner/work/test-container-env/test-container-env"
2023-10-06T13:18:10.1676080Z echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
2023-10-06T13:18:10.1676407Z echo "runner.temp=/home/runner/work/_temp"
2023-10-06T13:18:10.1676719Z echo "RUNNER_TEMP=${RUNNER_TEMP}"
2023-10-06T13:18:10.1680456Z shell: sh -e {0}
2023-10-06T13:18:10.1680716Z ##[endgroup]
2023-10-06T13:18:10.2860134Z github.workspace=/home/runner/work/test-container-env/test-container-env
2023-10-06T13:18:10.2861400Z GITHUB_WORKSPACE=/__w/test-container-env/test-container-env
2023-10-06T13:18:10.2862273Z runner.temp=/home/runner/work/_temp
2023-10-06T13:18:10.2862723Z RUNNER_TEMP=/__w/_temp
2023-10-06T13:18:10.3125889Z ##[group]Run echo "${GITHUB_CONTEXT}"
2023-10-06T13:18:10.3126226Z echo "${GITHUB_CONTEXT}"
2023-10-06T13:18:10.3126559Z shell: sh -e {0}
2023-10-06T13:18:10.3126781Z env:
2023-10-06T13:18:10.3143471Z GITHUB_CONTEXT: {
"token": "***",
"job": "run-tests",
"ref": "refs/heads/main",
"sha": "dc773c64217d12956bf5ce8a6452502dfcd0140f",
"repository": "nicola-lunghi/test-container-env",
"repository_owner": "nicola-lunghi",
"repository_owner_id": "25422924",
"repositoryUrl": "git://github.com/nicola-lunghi/test-container-env.git",
"run_id": "6432167437",
"run_number": "4",
"retention_days": "15",
"run_attempt": "1",
"artifact_cache_size_limit": "10",
"repository_visibility": "public",
"repo-self-hosted-runners-disabled": false,
"enterprise-managed-business-id": "",
"repository_id": "701344434",
"actor_id": "25422924",
"actor": "nicola-lunghi",
"triggering_actor": "nicola-lunghi",
"workflow": "Test Container Env",
"head_ref": "",
"base_ref": "",
"event_name": "push",
"event": {
"after": "dc773c64217d12956bf5ce8a6452502dfcd0140f",
"base_ref": null,
"before": "b58ce8b08fb82e0a3b66c5dd23b42d75b3f64c42",
"commits": [
{
"author": {
"email": "25422924+nicola-lunghi@users.noreply.github.com",
"name": "Nicola Lunghi",
"username": "nicola-lunghi"
},
"committer": {
"email": "noreply@github.com",
"name": "GitHub",
"username": "web-flow"
},
"distinct": true,
"id": "dc773c64217d12956bf5ce8a6452502dfcd0140f",
"message": "dump env context",
"timestamp": "2023-10-06T14:17:59+01:00",
"tree_id": "5dfb26916243af3e7a4ca3e293905d2ac0b72b02",
"url": "https://github.com/nicola-lunghi/test-container-env/commit/dc773c64217d12956bf5ce8a6452502dfcd0140f"
}
],
"compare": "https://github.com/nicola-lunghi/test-container-env/compare/b58ce8b08fb8...dc773c64217d",
"created": false,
"deleted": false,
"forced": false,
"head_commit": {
"author": {
"email": "25422924+nicola-lunghi@users.noreply.github.com",
"name": "Nicola Lunghi",
"username": "nicola-lunghi"
},
"committer": {
"email": "noreply@github.com",
"name": "GitHub",
"username": "web-flow"
},
"distinct": true,
"id": "dc773c64217d12956bf5ce8a6452502dfcd0140f",
"message": "dump env context",
"timestamp": "2023-10-06T14:17:59+01:00",
"tree_id": "5dfb26916243af3e7a4ca3e293905d2ac0b72b02",
"url": "https://github.com/nicola-lunghi/test-container-env/commit/dc773c64217d12956bf5ce8a6452502dfcd0140f"
},
"pusher": {
"email": "25422924+nicola-lunghi@users.noreply.github.com",
"name": "nicola-lunghi"
},
"ref": "refs/heads/main",
"repository": {
"allow_forking": true,
"archive_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/{archive_format}{/ref}",
"archived": false,
"assignees_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/assignees{/user}",
"blobs_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/git/blobs{/sha}",
"branches_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/branches{/branch}",
"clone_url": "https://github.com/nicola-lunghi/test-container-env.git",
"collaborators_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/collaborators{/collaborator}",
"comments_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/comments{/number}",
"commits_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/commits{/sha}",
"compare_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/compare/{base}...{head}",
"contents_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/contents/{+path}",
"contributors_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/contributors",
"created_at": 1696596747,
"default_branch": "main",
"deployments_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/deployments",
"description": "test container env variables",
"disabled": false,
"downloads_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/downloads",
"events_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/events",
"fork": false,
"forks": 0,
"forks_count": 0,
"forks_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/forks",
"full_name": "nicola-lunghi/test-container-env",
"git_commits_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/git/commits{/sha}",
"git_refs_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/git/refs{/sha}",
"git_tags_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/git/tags{/sha}",
"git_url": "git://github.com/nicola-lunghi/test-container-env.git",
"has_discussions": false,
"has_downloads": true,
"has_issues": false,
"has_pages": false,
"has_projects": false,
"has_wiki": false,
"homepage": null,
"hooks_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/hooks",
"html_url": "https://github.com/nicola-lunghi/test-container-env",
"id": 701344434,
"is_template": false,
"issue_comment_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/issues/comments{/number}",
"issue_events_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/issues/events{/number}",
"issues_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/issues{/number}",
"keys_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/keys{/key_id}",
"labels_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/labels{/name}",
"language": null,
"languages_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/languages",
"license": null,
"master_branch": "main",
"merges_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/merges",
"milestones_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/milestones{/number}",
"mirror_url": null,
"name": "test-container-env",
"node_id": "R_kgDOKc2qsg",
"notifications_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/notifications{?since,all,participating}",
"open_issues": 0,
"open_issues_count": 0,
"owner": {
"avatar_url": "https://avatars.githubusercontent.com/u/25422924?v=4",
"email": "25422924+nicola-lunghi@users.noreply.github.com",
"events_url": "https://api.github.com/users/nicola-lunghi/events{/privacy}",
"followers_url": "https://api.github.com/users/nicola-lunghi/followers",
"following_url": "https://api.github.com/users/nicola-lunghi/following{/other_user}",
"gists_url": "https://api.github.com/users/nicola-lunghi/gists{/gist_id}",
"gravatar_id": "",
"html_url": "https://github.com/nicola-lunghi",
"id": 25422924,
"login": "nicola-lunghi",
"name": "nicola-lunghi",
"node_id": "MDQ6VXNlcjI1NDIyOTI0",
"organizations_url": "https://api.github.com/users/nicola-lunghi/orgs",
"received_events_url": "https://api.github.com/users/nicola-lunghi/received_events",
"repos_url": "https://api.github.com/users/nicola-lunghi/repos",
"site_admin": false,
"starred_url": "https://api.github.com/users/nicola-lunghi/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/nicola-lunghi/subscriptions",
"type": "User",
"url": "https://api.github.com/users/nicola-lunghi"
},
"private": false,
"pulls_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/pulls{/number}",
"pushed_at": 1696598279,
"releases_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/releases{/id}",
"size": 0,
"ssh_url": "git@github.com:nicola-lunghi/test-container-env.git",
"stargazers": 0,
"stargazers_count": 0,
"stargazers_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/stargazers",
"statuses_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/statuses/{sha}",
"subscribers_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/subscribers",
"subscription_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/subscription",
"svn_url": "https://github.com/nicola-lunghi/test-container-env",
"tags_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/tags",
"teams_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/teams",
"topics": [],
"trees_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/git/trees{/sha}",
"updated_at": "2023-10-06T12:56:48Z",
"url": "https://github.com/nicola-lunghi/test-container-env",
"visibility": "public",
"watchers": 0,
"watchers_count": 0,
"web_commit_signoff_required": false
},
"sender": {
"avatar_url": "https://avatars.githubusercontent.com/u/25422924?v=4",
"events_url": "https://api.github.com/users/nicola-lunghi/events{/privacy}",
"followers_url": "https://api.github.com/users/nicola-lunghi/followers",
"following_url": "https://api.github.com/users/nicola-lunghi/following{/other_user}",
"gists_url": "https://api.github.com/users/nicola-lunghi/gists{/gist_id}",
"gravatar_id": "",
"html_url": "https://github.com/nicola-lunghi",
"id": 25422924,
"login": "nicola-lunghi",
"node_id": "MDQ6VXNlcjI1NDIyOTI0",
"organizations_url": "https://api.github.com/users/nicola-lunghi/orgs",
"received_events_url": "https://api.github.com/users/nicola-lunghi/received_events",
"repos_url": "https://api.github.com/users/nicola-lunghi/repos",
"site_admin": false,
"starred_url": "https://api.github.com/users/nicola-lunghi/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/nicola-lunghi/subscriptions",
"type": "User",
"url": "https://api.github.com/users/nicola-lunghi"
}
},
"server_url": "https://github.com",
"api_url": "https://api.github.com",
"graphql_url": "https://api.github.com/graphql",
"ref_name": "main",
"ref_protected": true,
"ref_type": "branch",
"secret_source": "Actions",
"workflow_ref": "nicola-lunghi/test-container-env/.github/workflows/test_container_envs.yml@refs/heads/main",
"workflow_sha": "dc773c64217d12956bf5ce8a6452502dfcd0140f",
"workspace": "/home/runner/work/test-container-env/test-container-env",
"action": "__run_2",
"event_path": "/home/runner/work/_temp/_github_workflow/event.json",
"action_repository": "",
"action_ref": "",
"path": "/home/runner/work/_temp/_runner_file_commands/add_path_9a5f7639-e36c-409b-a5df-9fe4b1a53cdc",
"env": "/home/runner/work/_temp/_runner_file_commands/set_env_9a5f7639-e36c-409b-a5df-9fe4b1a53cdc",
"step_summary": "/home/runner/work/_temp/_runner_file_commands/step_summary_9a5f7639-e36c-409b-a5df-9fe4b1a53cdc",
"state": "/home/runner/work/_temp/_runner_file_commands/save_state_9a5f7639-e36c-409b-a5df-9fe4b1a53cdc",
"output": "/home/runner/work/_temp/_runner_file_commands/set_output_9a5f7639-e36c-409b-a5df-9fe4b1a53cdc"
}
2023-10-06T13:18:10.3159635Z ##[endgroup]
2023-10-06T13:18:10.4197985Z {
2023-10-06T13:18:10.4198827Z "token": "***",
2023-10-06T13:18:10.4199415Z "job": "run-tests",
2023-10-06T13:18:10.4199766Z "ref": "refs/heads/main",
2023-10-06T13:18:10.4200235Z "sha": "dc773c64217d12956bf5ce8a6452502dfcd0140f",
2023-10-06T13:18:10.4200768Z "repository": "nicola-lunghi/test-container-env",
2023-10-06T13:18:10.4201600Z "repository_owner": "nicola-lunghi",
2023-10-06T13:18:10.4201988Z "repository_owner_id": "25422924",
2023-10-06T13:18:10.4202791Z "repositoryUrl": "git://github.com/nicola-lunghi/test-container-env.git",
2023-10-06T13:18:10.4203254Z "run_id": "6432167437",
2023-10-06T13:18:10.4203564Z "run_number": "4",
2023-10-06T13:18:10.4203804Z "retention_days": "15",
2023-10-06T13:18:10.4204057Z "run_attempt": "1",
2023-10-06T13:18:10.4204303Z "artifact_cache_size_limit": "10",
2023-10-06T13:18:10.4228691Z "repository_visibility": "public",
2023-10-06T13:18:10.4238825Z "repo-self-hosted-runners-disabled": false,
2023-10-06T13:18:10.4239385Z "enterprise-managed-business-id": "",
2023-10-06T13:18:10.4239725Z "repository_id": "701344434",
2023-10-06T13:18:10.4240087Z "actor_id": "25422924",
2023-10-06T13:18:10.4240402Z "actor": "nicola-lunghi",
2023-10-06T13:18:10.4240838Z "triggering_actor": "nicola-lunghi",
2023-10-06T13:18:10.4241213Z "workflow": "Test Container Env",
2023-10-06T13:18:10.4241493Z "head_ref": "",
2023-10-06T13:18:10.4241800Z "base_ref": "",
2023-10-06T13:18:10.4242059Z "event_name": "push",
2023-10-06T13:18:10.4242437Z "event": {
2023-10-06T13:18:10.4242750Z "after": "dc773c64217d12956bf5ce8a6452502dfcd0140f",
2023-10-06T13:18:10.4243096Z "base_ref": null,
2023-10-06T13:18:10.4243418Z "before": "b58ce8b08fb82e0a3b66c5dd23b42d75b3f64c42",
2023-10-06T13:18:10.4243724Z "commits": [
2023-10-06T13:18:10.4243997Z {
2023-10-06T13:18:10.4244332Z "author": {
2023-10-06T13:18:10.4246027Z "email": "25422924+nicola-lunghi@users.noreply.github.com",
2023-10-06T13:18:10.4246634Z "name": "Nicola Lunghi",
2023-10-06T13:18:10.4247274Z "username": "nicola-lunghi"
2023-10-06T13:18:10.4247700Z },
2023-10-06T13:18:10.4248318Z "committer": {
2023-10-06T13:18:10.4248837Z "email": "noreply@github.com",
2023-10-06T13:18:10.4249275Z "name": "GitHub",
2023-10-06T13:18:10.4250139Z "username": "web-flow"
2023-10-06T13:18:10.4251195Z },
2023-10-06T13:18:10.4251634Z "distinct": true,
2023-10-06T13:18:10.4252226Z "id": "dc773c64217d12956bf5ce8a6452502dfcd0140f",
2023-10-06T13:18:10.4252636Z "message": "dump env context",
2023-10-06T13:18:10.4253305Z "timestamp": "2023-10-06T14:17:59+01:00",
2023-10-06T13:18:10.4253883Z "tree_id": "5dfb26916243af3e7a4ca3e293905d2ac0b72b02",
2023-10-06T13:18:10.4254931Z "url": "https://github.com/nicola-lunghi/test-container-env/commit/dc773c64217d12956bf5ce8a6452502dfcd0140f"
2023-10-06T13:18:10.4255385Z }
2023-10-06T13:18:10.4256054Z ],
2023-10-06T13:18:10.4257110Z "compare": "https://github.com/nicola-lunghi/test-container-env/compare/b58ce8b08fb8...dc773c64217d",
2023-10-06T13:18:10.4257589Z "created": false,
2023-10-06T13:18:10.4258234Z "deleted": false,
2023-10-06T13:18:10.4258866Z "forced": false,
2023-10-06T13:18:10.4259512Z "head_commit": {
2023-10-06T13:18:10.4260161Z "author": {
2023-10-06T13:18:10.4261011Z "email": "25422924+nicola-lunghi@users.noreply.github.com",
2023-10-06T13:18:10.4261437Z "name": "Nicola Lunghi",
2023-10-06T13:18:10.4261927Z "username": "nicola-lunghi"
2023-10-06T13:18:10.4262247Z },
2023-10-06T13:18:10.4262906Z "committer": {
2023-10-06T13:18:10.4263599Z "email": "noreply@github.com",
2023-10-06T13:18:10.4264082Z "name": "GitHub",
2023-10-06T13:18:10.4264805Z "username": "web-flow"
2023-10-06T13:18:10.4265116Z },
2023-10-06T13:18:10.4265773Z "distinct": true,
2023-10-06T13:18:10.4266480Z "id": "dc773c64217d12956bf5ce8a6452502dfcd0140f",
2023-10-06T13:18:10.4266869Z "message": "dump env context",
2023-10-06T13:18:10.4267538Z "timestamp": "2023-10-06T14:17:59+01:00",
2023-10-06T13:18:10.4267951Z "tree_id": "5dfb26916243af3e7a4ca3e293905d2ac0b72b02",
2023-10-06T13:18:10.4268623Z "url": "https://github.com/nicola-lunghi/test-container-env/commit/dc773c64217d12956bf5ce8a6452502dfcd0140f"
2023-10-06T13:18:10.4269052Z },
2023-10-06T13:18:10.4269754Z "pusher": {
2023-10-06T13:18:10.4270824Z "email": "25422924+nicola-lunghi@users.noreply.github.com",
2023-10-06T13:18:10.4271330Z "name": "nicola-lunghi"
2023-10-06T13:18:10.4271811Z },
2023-10-06T13:18:10.4272498Z "ref": "refs/heads/main",
2023-10-06T13:18:10.4273062Z "repository": {
2023-10-06T13:18:10.4273725Z "allow_forking": true,
2023-10-06T13:18:10.4274586Z "archive_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/{archive_format}{/ref}",
2023-10-06T13:18:10.4275071Z "archived": false,
2023-10-06T13:18:10.4275817Z "assignees_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/assignees{/user}",
2023-10-06T13:18:10.4276527Z "blobs_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/git/blobs{/sha}",
2023-10-06T13:18:10.4277238Z "branches_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/branches{/branch}",
2023-10-06T13:18:10.4277891Z "clone_url": "https://github.com/nicola-lunghi/test-container-env.git",
2023-10-06T13:18:10.4278633Z "collaborators_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/collaborators{/collaborator}",
2023-10-06T13:18:10.4279390Z "comments_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/comments{/number}",
2023-10-06T13:18:10.4280097Z "commits_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/commits{/sha}",
2023-10-06T13:18:10.4280801Z "compare_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/compare/{base}...{head}",
2023-10-06T13:18:10.4281521Z "contents_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/contents/{+path}",
2023-10-06T13:18:10.4282237Z "contributors_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/contributors",
2023-10-06T13:18:10.4282701Z "created_at": 1696596747,
2023-10-06T13:18:10.4283414Z "default_branch": "main",
2023-10-06T13:18:10.4284419Z "deployments_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/deployments",
2023-10-06T13:18:10.4284946Z "description": "test container env variables",
2023-10-06T13:18:10.4285478Z "disabled": false,
2023-10-06T13:18:10.4286459Z "downloads_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/downloads",
2023-10-06T13:18:10.4287453Z "events_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/events",
2023-10-06T13:18:10.4287894Z "fork": false,
2023-10-06T13:18:10.4288782Z "forks": 0,
2023-10-06T13:18:10.4289293Z "forks_count": 0,
2023-10-06T13:18:10.4290461Z "forks_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/forks",
2023-10-06T13:18:10.4292081Z "full_name": "nicola-lunghi/test-container-env",
2023-10-06T13:18:10.4292653Z "git_commits_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/git/commits{/sha}",
2023-10-06T13:18:10.4293275Z "git_refs_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/git/refs{/sha}",
2023-10-06T13:18:10.4293883Z "git_tags_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/git/tags{/sha}",
2023-10-06T13:18:10.4294425Z "git_url": "git://github.com/nicola-lunghi/test-container-env.git",
2023-10-06T13:18:10.4294767Z "has_discussions": false,
2023-10-06T13:18:10.4295244Z "has_downloads": true,
2023-10-06T13:18:10.4295770Z "has_issues": false,
2023-10-06T13:18:10.4296283Z "has_pages": false,
2023-10-06T13:18:10.4296785Z "has_projects": false,
2023-10-06T13:18:10.4297205Z "has_wiki": false,
2023-10-06T13:18:10.4297791Z "homepage": null,
2023-10-06T13:18:10.4298614Z "hooks_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/hooks",
2023-10-06T13:18:10.4299411Z "html_url": "https://github.com/nicola-lunghi/test-container-env",
2023-10-06T13:18:10.4299857Z "id": 701344434,
2023-10-06T13:18:10.4300444Z "is_template": false,
2023-10-06T13:18:10.4301524Z "issue_comment_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/issues/comments{/number}",
2023-10-06T13:18:10.4302507Z "issue_events_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/issues/events{/number}",
2023-10-06T13:18:10.4303434Z "issues_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/issues{/number}",
2023-10-06T13:18:10.4304317Z "keys_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/keys{/key_id}",
2023-10-06T13:18:10.4305196Z "labels_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/labels{/name}",
2023-10-06T13:18:10.4305638Z "language": null,
2023-10-06T13:18:10.4306576Z "languages_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/languages",
2023-10-06T13:18:10.4307028Z "license": null,
2023-10-06T13:18:10.4307633Z "master_branch": "main",
2023-10-06T13:18:10.4308464Z "merges_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/merges",
2023-10-06T13:18:10.4309367Z "milestones_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/milestones{/number}",
2023-10-06T13:18:10.4309927Z "mirror_url": null,
2023-10-06T13:18:10.4310527Z "name": "test-container-env",
2023-10-06T13:18:10.4311060Z "node_id": "R_kgDOKc2qsg",
2023-10-06T13:18:10.4312015Z "notifications_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/notifications{?since,all,participating}",
2023-10-06T13:18:10.4312623Z "open_issues": 0,
2023-10-06T13:18:10.4313141Z "open_issues_count": 0,
2023-10-06T13:18:10.4313540Z "owner": {
2023-10-06T13:18:10.4314518Z "avatar_url": "https://avatars.githubusercontent.com/u/25422924?v=4",
2023-10-06T13:18:10.4315224Z "email": "25422924+nicola-lunghi@users.noreply.github.com",
2023-10-06T13:18:10.4315842Z "events_url": "https://api.github.com/users/nicola-lunghi/events{/privacy}",
2023-10-06T13:18:10.4316469Z "followers_url": "https://api.github.com/users/nicola-lunghi/followers",
2023-10-06T13:18:10.4317125Z "following_url": "https://api.github.com/users/nicola-lunghi/following{/other_user}",
2023-10-06T13:18:10.4317760Z "gists_url": "https://api.github.com/users/nicola-lunghi/gists{/gist_id}",
2023-10-06T13:18:10.4318439Z "gravatar_id": "",
2023-10-06T13:18:10.4319365Z "html_url": "https://github.com/nicola-lunghi",
2023-10-06T13:18:10.4319763Z "id": 25422924,
2023-10-06T13:18:10.4320571Z "login": "nicola-lunghi",
2023-10-06T13:18:10.4320925Z "name": "nicola-lunghi",
2023-10-06T13:18:10.4321439Z "node_id": "MDQ6VXNlcjI1NDIyOTI0",
2023-10-06T13:18:10.4322195Z "organizations_url": "https://api.github.com/users/nicola-lunghi/orgs",
2023-10-06T13:18:10.4322847Z "received_events_url": "https://api.github.com/users/nicola-lunghi/received_events",
2023-10-06T13:18:10.4323455Z "repos_url": "https://api.github.com/users/nicola-lunghi/repos",
2023-10-06T13:18:10.4323884Z "site_admin": false,
2023-10-06T13:18:10.4324799Z "starred_url": "https://api.github.com/users/nicola-lunghi/starred{/owner}{/repo}",
2023-10-06T13:18:10.4325477Z "subscriptions_url": "https://api.github.com/users/nicola-lunghi/subscriptions",
2023-10-06T13:18:10.4325917Z "type": "User",
2023-10-06T13:18:10.4326795Z "url": "https://api.github.com/users/nicola-lunghi"
2023-10-06T13:18:10.4327177Z },
2023-10-06T13:18:10.4327887Z "private": false,
2023-10-06T13:18:10.4328830Z "pulls_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/pulls{/number}",
2023-10-06T13:18:10.4329300Z "pushed_at": 1696598279,
2023-10-06T13:18:10.4331547Z "releases_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/releases{/id}",
2023-10-06T13:18:10.4332021Z "size": 0,
2023-10-06T13:18:10.4332946Z "ssh_url": "git@github.com:nicola-lunghi/test-container-env.git",
2023-10-06T13:18:10.4333569Z "stargazers": 0,
2023-10-06T13:18:10.4333922Z "stargazers_count": 0,
2023-10-06T13:18:10.4334994Z "stargazers_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/stargazers",
2023-10-06T13:18:10.4335743Z "statuses_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/statuses/{sha}",
2023-10-06T13:18:10.4336447Z "subscribers_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/subscribers",
2023-10-06T13:18:10.4337173Z "subscription_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/subscription",
2023-10-06T13:18:10.4337817Z "svn_url": "https://github.com/nicola-lunghi/test-container-env",
2023-10-06T13:18:10.4338427Z "tags_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/tags",
2023-10-06T13:18:10.4339085Z "teams_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/teams",
2023-10-06T13:18:10.4339512Z "topics": [],
2023-10-06T13:18:10.4340526Z "trees_url": "https://api.github.com/repos/nicola-lunghi/test-container-env/git/trees{/sha}",
2023-10-06T13:18:10.4341090Z "updated_at": "2023-10-06T12:56:48Z",
2023-10-06T13:18:10.4341765Z "url": "https://github.com/nicola-lunghi/test-container-env",
2023-10-06T13:18:10.4342286Z "visibility": "public",
2023-10-06T13:18:10.4342784Z "watchers": 0,
2023-10-06T13:18:10.4343510Z "watchers_count": 0,
2023-10-06T13:18:10.4344237Z "web_commit_signoff_required": false
2023-10-06T13:18:10.4344761Z },
2023-10-06T13:18:10.4345494Z "sender": {
2023-10-06T13:18:10.4346331Z "avatar_url": "https://avatars.githubusercontent.com/u/25422924?v=4",
2023-10-06T13:18:10.4347011Z "events_url": "https://api.github.com/users/nicola-lunghi/events{/privacy}",
2023-10-06T13:18:10.4347635Z "followers_url": "https://api.github.com/users/nicola-lunghi/followers",
2023-10-06T13:18:10.4348259Z "following_url": "https://api.github.com/users/nicola-lunghi/following{/other_user}",
2023-10-06T13:18:10.4348899Z "gists_url": "https://api.github.com/users/nicola-lunghi/gists{/gist_id}",
2023-10-06T13:18:10.4349319Z "gravatar_id": "",
2023-10-06T13:18:10.4350179Z "html_url": "https://github.com/nicola-lunghi",
2023-10-06T13:18:10.4350810Z "id": 25422924,
2023-10-06T13:18:10.4351614Z "login": "nicola-lunghi",
2023-10-06T13:18:10.4352158Z "node_id": "MDQ6VXNlcjI1NDIyOTI0",
2023-10-06T13:18:10.4352910Z "organizations_url": "https://api.github.com/users/nicola-lunghi/orgs",
2023-10-06T13:18:10.4353539Z "received_events_url": "https://api.github.com/users/nicola-lunghi/received_events",
2023-10-06T13:18:10.4354151Z "repos_url": "https://api.github.com/users/nicola-lunghi/repos",
2023-10-06T13:18:10.4354558Z "site_admin": false,
2023-10-06T13:18:10.4355511Z "starred_url": "https://api.github.com/users/nicola-lunghi/starred{/owner}{/repo}",
2023-10-06T13:18:10.4356196Z "subscriptions_url": "https://api.github.com/users/nicola-lunghi/subscriptions",
2023-10-06T13:18:10.4356641Z "type": "User",
2023-10-06T13:18:10.4357522Z "url": "https://api.github.com/users/nicola-lunghi"
2023-10-06T13:18:10.4357904Z }
2023-10-06T13:18:10.4358594Z },
2023-10-06T13:18:10.4359511Z "server_url": "https://github.com",
2023-10-06T13:18:10.4360198Z "api_url": "https://api.github.com",
2023-10-06T13:18:10.4360942Z "graphql_url": "https://api.github.com/graphql",
2023-10-06T13:18:10.4361287Z "ref_name": "main",
2023-10-06T13:18:10.4362074Z "ref_protected": true,
2023-10-06T13:18:10.4362604Z "ref_type": "branch",
2023-10-06T13:18:10.4363294Z "secret_source": "Actions",
2023-10-06T13:18:10.4364331Z "workflow_ref": "nicola-lunghi/test-container-env/.github/workflows/test_container_envs.yml@refs/heads/main",
2023-10-06T13:18:10.4364886Z "workflow_sha": "dc773c64217d12956bf5ce8a6452502dfcd0140f",
2023-10-06T13:18:10.4365398Z "workspace": "/home/runner/work/test-container-env/test-container-env",
2023-10-06T13:18:10.4366026Z "action": "__run_2",
2023-10-06T13:18:10.4366454Z "event_path": "/home/runner/work/_temp/_github_workflow/event.json",
2023-10-06T13:18:10.4366799Z "action_repository": "",
2023-10-06T13:18:10.4367312Z "action_ref": "",
2023-10-06T13:18:10.4368326Z "path": "/home/runner/work/_temp/_runner_file_commands/add_path_9a5f7639-e36c-409b-a5df-9fe4b1a53cdc",
2023-10-06T13:18:10.4369031Z "env": "/home/runner/work/_temp/_runner_file_commands/set_env_9a5f7639-e36c-409b-a5df-9fe4b1a53cdc",
2023-10-06T13:18:10.4369730Z "step_summary": "/home/runner/work/_temp/_runner_file_commands/step_summary_9a5f7639-e36c-409b-a5df-9fe4b1a53cdc",
2023-10-06T13:18:10.4370685Z "state": "/home/runner/work/_temp/_runner_file_commands/save_state_9a5f7639-e36c-409b-a5df-9fe4b1a53cdc",
2023-10-06T13:18:10.4371370Z "output": "/home/runner/work/_temp/_runner_file_commands/set_output_9a5f7639-e36c-409b-a5df-9fe4b1a53cdc"
2023-10-06T13:18:10.4371780Z }
2023-10-06T13:18:10.4397219Z ##[group]Run echo "${RUNNER_CONTEXT}"
2023-10-06T13:18:10.4397545Z echo "${RUNNER_CONTEXT}"
2023-10-06T13:18:10.4397858Z shell: sh -e {0}
2023-10-06T13:18:10.4398075Z env:
2023-10-06T13:18:10.4398584Z RUNNER_CONTEXT: {
"os": "Linux",
"arch": "X64",
"name": "GitHub Actions 2",
"environment": "github-hosted",
"tool_cache": "/opt/hostedtoolcache",
"temp": "/home/runner/work/_temp",
"workspace": "/home/runner/work/test-container-env"
}
2023-10-06T13:18:10.4399125Z ##[endgroup]
2023-10-06T13:18:10.5262053Z {
2023-10-06T13:18:10.5262496Z "os": "Linux",
2023-10-06T13:18:10.5262770Z "arch": "X64",
2023-10-06T13:18:10.5263281Z "name": "GitHub Actions 2",
2023-10-06T13:18:10.5263979Z "environment": "github-hosted",
2023-10-06T13:18:10.5264433Z "tool_cache": "/opt/hostedtoolcache",
2023-10-06T13:18:10.5264859Z "temp": "/home/runner/work/_temp",
2023-10-06T13:18:10.5265428Z "workspace": "/home/runner/work/test-container-env"
2023-10-06T13:18:10.5265993Z }
2023-10-06T13:18:10.5325184Z ##[group]Run echo "${ENV_CONTEXT}"
2023-10-06T13:18:10.5325519Z echo "${ENV_CONTEXT}"
2023-10-06T13:18:10.5325845Z shell: sh -e {0}
2023-10-06T13:18:10.5326042Z env:
2023-10-06T13:18:10.5326251Z ENV_CONTEXT: {}
2023-10-06T13:18:10.5326486Z ##[endgroup]
2023-10-06T13:18:10.6272794Z {}
2023-10-06T13:18:10.6325722Z ##[group]Run env | sort
2023-10-06T13:18:10.6326167Z env | sort
2023-10-06T13:18:10.6326617Z shell: sh -e {0}
2023-10-06T13:18:10.6326913Z ##[endgroup]
2023-10-06T13:18:10.7451172Z CI=true
2023-10-06T13:18:10.7451709Z GITHUB_ACTION=__run_5
2023-10-06T13:18:10.7452146Z GITHUB_ACTIONS=true
2023-10-06T13:18:10.7465901Z GITHUB_ACTION_REF=
2023-10-06T13:18:10.7466255Z GITHUB_ACTION_REPOSITORY=
2023-10-06T13:18:10.7466785Z GITHUB_ACTOR=nicola-lunghi
2023-10-06T13:18:10.7467219Z GITHUB_ACTOR_ID=25422924
2023-10-06T13:18:10.7467607Z GITHUB_API_URL=https://api.github.com
2023-10-06T13:18:10.7467904Z GITHUB_BASE_REF=
2023-10-06T13:18:10.7468448Z GITHUB_ENV=/__w/_temp/_runner_file_commands/set_env_ca1ecde1-8737-4698-9c03-e8f7b242ef52
2023-10-06T13:18:10.7468862Z GITHUB_EVENT_NAME=push
2023-10-06T13:18:10.7469301Z GITHUB_EVENT_PATH=/github/workflow/event.json
2023-10-06T13:18:10.7469669Z GITHUB_GRAPHQL_URL=https://api.github.com/graphql
2023-10-06T13:18:10.7470216Z GITHUB_HEAD_REF=
2023-10-06T13:18:10.7470517Z GITHUB_JOB=run-tests
2023-10-06T13:18:10.7471140Z GITHUB_OUTPUT=/__w/_temp/_runner_file_commands/set_output_ca1ecde1-8737-4698-9c03-e8f7b242ef52
2023-10-06T13:18:10.7471762Z GITHUB_PATH=/__w/_temp/_runner_file_commands/add_path_ca1ecde1-8737-4698-9c03-e8f7b242ef52
2023-10-06T13:18:10.7472121Z GITHUB_REF=refs/heads/main
2023-10-06T13:18:10.7472432Z GITHUB_REF_NAME=main
2023-10-06T13:18:10.7472823Z GITHUB_REF_PROTECTED=true
2023-10-06T13:18:10.7473102Z GITHUB_REF_TYPE=branch
2023-10-06T13:18:10.7473536Z GITHUB_REPOSITORY=nicola-lunghi/test-container-env
2023-10-06T13:18:10.7473914Z GITHUB_REPOSITORY_ID=701344434
2023-10-06T13:18:10.7474335Z GITHUB_REPOSITORY_OWNER=nicola-lunghi
2023-10-06T13:18:10.7474714Z GITHUB_REPOSITORY_OWNER_ID=25422924
2023-10-06T13:18:10.7475055Z GITHUB_RETENTION_DAYS=15
2023-10-06T13:18:10.7475365Z GITHUB_RUN_ATTEMPT=1
2023-10-06T13:18:10.7475629Z GITHUB_RUN_ID=6432167437
2023-10-06T13:18:10.7475940Z GITHUB_RUN_NUMBER=4
2023-10-06T13:18:10.7476376Z GITHUB_SERVER_URL=https://github.com
2023-10-06T13:18:10.7476716Z GITHUB_SHA=dc773c64217d12956bf5ce8a6452502dfcd0140f
2023-10-06T13:18:10.7477289Z GITHUB_STATE=/__w/_temp/_runner_file_commands/save_state_ca1ecde1-8737-4698-9c03-e8f7b242ef52
2023-10-06T13:18:10.7477953Z GITHUB_STEP_SUMMARY=/__w/_temp/_runner_file_commands/step_summary_ca1ecde1-8737-4698-9c03-e8f7b242ef52
2023-10-06T13:18:10.7478410Z GITHUB_TRIGGERING_ACTOR=nicola-lunghi
2023-10-06T13:18:10.7478843Z GITHUB_WORKFLOW=Test Container Env
2023-10-06T13:18:10.7479452Z GITHUB_WORKFLOW_REF=nicola-lunghi/test-container-env/.github/workflows/test_container_envs.yml@refs/heads/main
2023-10-06T13:18:10.7479915Z GITHUB_WORKFLOW_SHA=dc773c64217d12956bf5ce8a6452502dfcd0140f
2023-10-06T13:18:10.7480440Z GITHUB_WORKSPACE=/__w/test-container-env/test-container-env
2023-10-06T13:18:10.7480864Z HOME=/github/home
2023-10-06T13:18:10.7481198Z HOSTNAME=82749e3b34d9
2023-10-06T13:18:10.7481528Z PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2023-10-06T13:18:10.7482459Z ***
2023-10-06T13:18:10.7482711Z RUNNER_ARCH=X64
2023-10-06T13:18:10.7483105Z RUNNER_ENVIRONMENT=github-hosted
2023-10-06T13:18:10.7483454Z RUNNER_NAME=GitHub Actions 2
2023-10-06T13:18:10.7483722Z RUNNER_OS=Linux
2023-10-06T13:18:10.7484139Z RUNNER_TEMP=/__w/_temp
2023-10-06T13:18:10.7484450Z RUNNER_TOOL_CACHE=/__t
2023-10-06T13:18:10.7484816Z RUNNER_WORKSPACE=/__w/test-container-env
2023-10-06T13:18:10.7513096Z ##[group]Run echo "Test File" > "${RUNNER_TEMP}/log.txt"
2023-10-06T13:18:10.7513569Z echo "Test File" > "${RUNNER_TEMP}/log.txt"
2023-10-06T13:18:10.7513959Z cat "${RUNNER_TEMP}/log.txt"
2023-10-06T13:18:10.7514306Z shell: sh -e {0}
2023-10-06T13:18:10.7514603Z ##[endgroup]
2023-10-06T13:18:10.8546660Z Test File
2023-10-06T13:18:10.8803062Z ##[group]Run actions/upload-artifact@v3
2023-10-06T13:18:10.8803396Z with:
2023-10-06T13:18:10.8803610Z name: test-results
2023-10-06T13:18:10.8803861Z if-no-files-found: error
2023-10-06T13:18:10.8804372Z path: /log.txt

2023-10-06T13:18:10.8804590Z ##[endgroup]
2023-10-06T13:18:10.8910261Z ##[command]/usr/bin/docker exec 82749e3b34d9c93658fe36c820b84f422e43b5161cfcc607cd69949eab3c0fe6 sh -c "cat /etc/*release | grep ^ID"
2023-10-06T13:18:11.2995297Z ##[error]No files were found with the provided path: /log.txt. No artifacts will be uploaded.
2023-10-06T13:18:11.3127817Z Stop and remove container: 01832559a3e347b59e23a7f57fca9b63_ubuntu2004_cff52c
2023-10-06T13:18:11.3133668Z ##[command]/usr/bin/docker rm --force 82749e3b34d9c93658fe36c820b84f422e43b5161cfcc607cd69949eab3c0fe6
2023-10-06T13:18:11.4715623Z 82749e3b34d9c93658fe36c820b84f422e43b5161cfcc607cd69949eab3c0fe6
2023-10-06T13:18:11.4840746Z Remove container network: github_network_a5f2de3aaa54493088ab51da83b24320
2023-10-06T13:18:11.4846562Z ##[command]/usr/bin/docker network rm github_network_a5f2de3aaa54493088ab51da83b24320
2023-10-06T13:18:11.6874001Z github_network_a5f2de3aaa54493088ab51da83b24320
2023-10-06T13:18:11.7051465Z Cleaning up orphan processes
```

**Comment by nikaro** [comment]
This is still an issue, cf. https://github.com/pypa/gh-action-pypi-publish/issues/300
