### ISSUE TITLE
The operation was canceled.

### ISSUE THREAD

**Issue by magnetnation** [actions/runner#2468]
**Describe the bug**
Since last week actions in our different repositories started to fail with similar error:

#[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

**To Reproduce**
1. Go to Actions
2. Run or re-run any job
3. See error mentioned above

**Expected behavior**
Workflow should be running without cancellations.

## Runner Version and Platform
Image: ubuntu-22.04
Version: 20230219.1
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230219.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230219.1

OS of the machine running the runner?
Linux

## What's not working?
Workflow is failing without any reason stated in the logs, apart from it has been cancelled.

## Job Log Output
2023-03-01T06:49:56.3959504Z > @mgnation/mgdata@1.4.212 _bundle
2023-03-01T06:49:56.3960408Z > node build/bundle.js
2023-03-01T06:49:56.3960710Z 
2023-03-01T06:49:56.8884234Z [32mBundling has started[0m
2023-03-01T06:49:56.9282005Z [34mCopy results completed[0m
2023-03-01T06:49:56.9290747Z [34mAllow publish completed[0m
2023-03-01T06:49:56.9295155Z build: 39.141ms
2023-03-01T06:49:56.9302039Z [32mBundling has finished[0m
2023-03-01T06:49:57.2702808Z 
2023-03-01T06:49:57.2708891Z > @mgnation/mgdata@1.4.212 test
2023-03-01T06:49:57.2709823Z > node ./node_modules/nyc/bin/nyc.js node ./tmp/spec/runner.js
2023-03-01T06:49:57.2710190Z 
2023-03-01T06:50:56.1865343Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2023-03-01T06:50:56.2969758Z ##[debug]Re-evaluate condition on job cancellation for step: 'npm install, build, and test'.
2023-03-01T06:50:56.2973354Z ##[debug]Skip Re-evaluate condition on runner shutdown.
2023-03-01T06:50:56.5597757Z ----------|---------|----------|---------|---------|-------------------
2023-03-01T06:50:56.5612354Z File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
2023-03-01T06:50:56.5616821Z ----------|---------|----------|---------|---------|-------------------
2023-03-01T06:50:56.5618821Z All files |       0 |        0 |       0 |       0 |                   
2023-03-01T06:50:56.5620688Z ----------|---------|----------|---------|---------|-------------------
2023-03-01T06:50:56.6038836Z ##[error]The operation was canceled.
2023-03-01T06:50:56.6052060Z ##[debug]System.OperationCanceledException: The operation was canceled.
2023-03-01T06:50:56.6060563Z ##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
2023-03-01T06:50:56.6063113Z ##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
2023-03-01T06:50:56.6065859Z ##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
2023-03-01T06:50:56.6069900Z ##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
2023-03-01T06:50:56.6078953Z ##[debug]   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
2023-03-01T06:50:56.6079410Z ##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
2023-03-01T06:50:56.6086736Z ##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2023-03-01T06:50:56.6102555Z ##[debug]Finishing: npm install, build, and test
2023-03-01T06:50:56.6376954Z ##[debug]Evaluating condition for step: 'Post Use Node.js 16.x'
2023-03-01T06:50:56.6379186Z ##[debug]Skip evaluate condition on runner shutdown.
2023-03-01T06:50:56.6392406Z ##[debug]Evaluating condition for step: 'Post Run actions/checkout@v3'
2023-03-01T06:50:56.6392834Z ##[debug]Skip evaluate condition on runner shutdown.
2023-03-01T06:50:56.6821240Z ##[debug]Starting: Complete job
2023-03-01T06:50:56.6833228Z Uploading runner diagnostic logs
2023-03-01T06:50:56.7043348Z ##[debug]Starting diagnostic file upload.
2023-03-01T06:50:56.7046324Z ##[debug]Setting up diagnostic log folders.
2023-03-01T06:50:56.7306655Z ##[debug]Creating diagnostic log files folder.
2023-03-01T06:50:56.7419356Z ##[debug]Copying 1 worker diagnostic logs.
2023-03-01T06:50:56.7470424Z ##[debug]Copying 1 runner diagnostic logs.
2023-03-01T06:50:56.7539403Z ##[debug]Zipping diagnostic files.
2023-03-01T06:50:56.8067735Z ##[debug]Uploading diagnostic metadata file.
2023-03-01T06:50:56.8441811Z ##[debug]Diagnostic file upload complete.
2023-03-01T06:50:56.8445882Z Completed runner diagnostic log upload
2023-03-01T06:50:56.8450728Z Cleaning up orphan processes
2023-03-01T06:50:56.9100720Z ##[debug]Finishing: Complete job
2023-03-01T06:50:56.9301578Z ##[debug]Finishing: build (16.x)

**Comment by jarreds** [comment]
This has recently stated happening at an onerous frequency in our Bazel monorepo build action. Self-hosted runner. Happy to provide any troubleshooting info I can.

Summary:

> **Bazel Build**
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
> **Bazel Build**
The operation was canceled.

**Comment by ruvceskistefan** [comment]
Hey all, 

@magnetnation are you running hosted runner or using our image for self-hosted runner?
Also, could you provide us with job URLs(it's ok if the repo is private) so we can check the logs?

**Comment by magnetnation** [comment]
Hi,

We are using hosted runners, and here is an example of [failed run](https://github.com/mgnation/mgData/actions/runs/4286089713/jobs/7497442345)

**Comment by matsest** [comment]
Also see this a lot in various PowerShell commands that run. Seems to be very unpredictable, but definitely seeing this a lot across multiple jobs and commands. Have not seen this previously to this extent.

**Comment by magnetnation** [comment]
Any update on this issue?
None of our actions can go through since then.

**Comment by matsest** [comment]
Same here, still seeing these issues @ruvceskistefan

**Comment by igordrnobrega** [comment]
Any updated on this? I've this issue for a week now and nothing seems to be solving it

**Comment by nuhkoca** [comment]
We have also been facing this issue very frequently for weeks now even with a 8-core larger runner. How can I upload a shutdown log before the runner dies? It could have given an insight to me actually.

**Comment by credativ-dar** [comment]
@ruvceskistefan I think the tag "awaiting-customer-response" is not appropriate any more, could you remove it?
```
https://github.com/credativ/vali/actions/runs/4467520060/jobs/7847403788

**Comment by edergillian-eeg** [comment]
This issue started happening after I transferred a repository from one organization to another. It was working when the repo was on the other organization and now all jobs are being cancelled, no exception.

There's no timeout set on the workflow file and the cancellation can happen anytime between ~30s and ~1m.

Both organizations have exactly the same configuration and paid plan. Other repositories' workflows in the organization run just fine, including other transferred repositories.

When I re-ran the failed jobs with debug log enabled, the only error I get on the Runner logs is this:

```
[2023-03-22 02:35:37Z ERR  GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/<big_hash>/_apis/distributedtask/pools/2/messages?sessionId=<big_session_id>&lastMessageId=597&status=Online&runnerVersion=2.303.0 failed. HTTP Status: Forbidden, AFD Ref: Ref A: BFA7EEED124B494B83E44B4AB4DCA200 Ref B: BN3EDGE0703 Ref C: 2023-03-22T02:35:37Z
[2023-03-22 02:35:37Z INFO MessageListener] Runner OAuth token has been revoked. Unable to pull message.
```

**Comment by Milamary** [comment]
Having similar issue with Runner version: '2.303.0', Runner: 'ubuntu-latest-16-cores'.
It randomly fails builds with `- Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)`

**Comment by jsjoeio** [comment]
This is happening to us as well on a monorepo (Turborepo) in the Lint job (running with ESLint).

**Comment by nuhkoca** [comment]
We fixed it by limiting workers on a 8 Core machine with:

`org.gradle.workers.max = 4`

**Comment by mathemaphysics** [comment]
@nuhcoka I'm confused because my CMake build should only run a single thread unless the -j flag is given (when build system is make or ninja). That's why I assumed it wasn't the issue.

Maybe the default setting changed.

**Comment by nuhkoca** [comment]
@mathemaphysics but Gradle by default uses all cores no?. The official description of the flag:

> `org.gradle.workers.max=(max # of worker processes)`
> When configured, Gradle will use a maximum of the given number of workers. See also [performance command-line options](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_performance). Default is number of CPU processors.

**Comment by sundarvenkata-EBI** [comment]
We are having a similar issue as well. See [here](https://github.com/EBIvariation/eva-common-pyutils/actions/runs/4873276091/jobs/8739528555?pr=36)

**Comment by netsgnut** [comment]
> We are having a similar issue as well where we have a process running for a really long time (like 6 hours) before it fails for no reason. See [here](https://github.com/EBIvariation/eva-common-pyutils/actions/runs/4873276091/jobs/8739528555?pr=36)

I think your case may be different from others here. It is related to the 6-hour job execution limit instead. From the [docs](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits),
> Job execution time - Each job in a workflow can run for up to 6 hours of execution time. If a job reaches this limit, the job is terminated and fails to complete.

**Comment by deathemperor** [comment]
> 

We're constantly having issue with this. it's unusable. until it's fixed we have to run it manually every time. link to action https://github.com/papaya-insurtech/berry/actions/runs/5146011637/jobs/9264458485

**Comment by bvdmitri** [comment]
We were able to fix it on our side, we had a mistake in our codebase that caused enormous amount of unnecessary allocations. We no longer have any issues after the mistake has been fixed. It looks like the "The operation was cancelled" error was definitely an OOM error, but getting a better error message would be nicer.

**Comment by nuhkoca** [comment]
> We were able to fix it on our side, we had a mistake in our codebase that caused enormous amount of unnecessary allocations. We no longer have any issues after the mistake has been fixed. It looks like the "The operation was cancelled" error was definitely an OOM error, but getting a better error message would be nicer.

Hey @bvdmitri, what was the fix exactly? Maybe it can shed some light on ours, too 🙂

**Comment by bvdmitri** [comment]
@nuhkoca 
Well, we refactored our code such that it allocated and used less memory. 
Nothing specific to the Github actions runner.

**Comment by a1300** [comment]
For me roughly every third github action failed. Increasing the **swap space** to 10GB on the `ubuntu-latest` runner with github action [pierotofy/set-swap-space](https://github.com/pierotofy/set-swap-space) fixed the problem for me.

```yaml
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

```

**Comment by nuhkoca** [comment]
We also switched over to a new next gen garbage collector and it fixed most OOM problems.

instead of `-XX:+UseParallelGC`

`-XX:+UseConcMarkSweepGC`

This flag is needed to activate the CMS Collector in the first place. By default, HotSpot uses the Throughput Collector instead.

`-XX:+UseParNewGC`

When the CMS collector is used, this flag activates the parallel execution of young generation GCs using multiple threads. It may seem surprising at first that we cannot simply reuse the flag -XX:+UseParallelGC known from the Throughput Collector, because conceptually the young generation GC algorithms used are the same. However, since the interplay between the young generation GC algorithm and the old generation GC algorithm is different with the CMS collector, there are two different implementations of young generation GC and thus two different flags.

https://www.codecentric.de/wissens-hub/blog/useful-jvm-flags-part-7-cms-collector

**Comment by kaanx022** [comment]
for me nothing works. I couldn't even find an image, or an example that works. Tried in a matrix, java and SDK combinations, all images, all platforms, all the different things. 

This is so frustrating. Why won't you people give us an example that just works ? Every single time I have to build a CI from scratch every few years, I have to go through this god damn rabbit hole. What is wrong with you people

https://github.com/kaanx022/kaan/actions/runs/9042209780/job/24848448703

**Comment by kaanx022** [comment]
ok on ubuntu some of them are actually running with the perfect setup, the big matrix table is here: 

https://github.com/kaanx022/kaan/actions/runs/9042456492/job/24848994152


But we shouldn't have to run a matrix of ALL POSSIBLE COMBINATIONS just to figure out the one that works.

**Comment by wffurr** [comment]
This seems to still be happening, e.g. with `sudo apt-get install -y libtinfo5`.  See also https://github.com/actions/runner-images/issues/9959.  Removing the `needrestart` service seems to work around the issue.

**Comment by webdev-faizan** [comment]
@ruvceskistefan
I have the same issue:
![image](https://github.com/user-attachments/assets/00cf6dd4-a969-45fa-bfc4-78d3a6af35e5)

**Comment by SantiiRepair** [comment]
Am I late for the party?

![image](https://github.com/user-attachments/assets/031d7af5-3d1b-4d2d-9f87-88065efa233d)

**Comment by mathemaphysics** [comment]
@SantiiRepair It seems there was never really a resolution. I still get my cmake build dying. The only other time I've seen something like this happen locally on one of my own machines is when the CPU was just taxed beyond its capability. 

My guess is that they just don't have the compute power or something.

**Comment by SantiiRepair** [comment]
> @SantiiRepair It seems there was never really a resolution. I still get my cmake build dying. The only other time I've seen something like this happen locally on one of my own machines is when the CPU was just taxed beyond its capability.
> 
> My guess is that they just don't have the compute power or something.

Maybe I've fixed it, I have another error in my workflow but it's not related to this now, I've added `timeout-minutes` and `fail-fast` and the previous error is gone

![image](https://github.com/user-attachments/assets/1f074b07-45c6-4d80-8a94-80e5b6dd78e8)

**Comment by titanism** [comment]
The previous commented fix (https://github.com/actions/runner/issues/2468#issuecomment-2543395161) **did not** resolve the issue, we still get `Error: The operation was canceled.` error with @forwardemail's monorepo.  

Ref: <https://github.com/forwardemail/forwardemail.net/commit/26efbd68ceec53466c7a254b30bc5ba8dfeac1a4#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721>

**Comment by titanism** [comment]
https://x.com/fwdemail/status/2015782464438866300

**Comment by tay1orjones** [comment]
More reports of what appears to be the same thing over in https://github.com/actions/runner-images/issues/13263

**Comment by tay1orjones** [comment]
We've moved to using a larger runner (8 core linux, 32GB RAM, 300GB disk) which fixed the issue for us. Problem is, it's expensive and I want to move off of it. 

I opened a new PR to test and it failed again right off the bat: https://github.com/carbon-design-system/carbon/actions/runs/22144703661/job/64018354752?pr=21568

**Comment by Eskat0n** [comment]
We're experiencing the same issue in our runs as well (on a private repo, hence I can't share the run details). Observed frequency of these seemingly random cancellations became much higher in the last 30 days or so.
```
[2026-02-19 07:30:07Z INFO HostContext] Runner will be shutdown for UserCancelled
[2026-02-19 07:30:07Z INFO StepsRunner] Cancel current running step.
```

**Comment by Barre** [comment]
I'm getting this a bunch with Github hosted runners as of today.

Example: https://github.com/Barre/ZeroFS/actions/runs/22480743922/job/65120241358?pr=357

> 2026-02-27T10:40:14.3827052Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

**Comment by mehmet-oakslab** [comment]
We are getting this error on our private repo with GitHub hosted runners as well, retrying helps most of the time. In one occasion I retried several times but it was always failing, I ended up creating a new branch with the same commits and it worked right away. May be a coincidence, I couldn't find a reliable way to reproduce.

**Comment by Barre** [comment]
Here's the reply I got from github support 

<img width="777" height="297" alt="Image" src="https://github.com/user-attachments/assets/5928baa8-ca9a-4228-bc6b-81963704d8a9" />

**Comment by alexTr3** [comment]
I also have this and its totally unacceptable that we dont have any other information with the error message...

**Comment by bfops** [comment]
Our org has migrated to self-hosted runners to avoid this issue. That has been a big rabbit hole though, so if I were to do it over I would probably just migrate to something else entirely, e.g. Jenkins.

**Comment by sakshi2k** [comment]
Facing same issue here even after multiple tries. Find logs and link to the failed run below:

- [Link to Failed run with Debug On](https://github.com/sakshi2k/wisdom-reels/actions/runs/32996371914/job/98267978164)
- [Link to Detailed Logs ](https://productionresultssa19.blob.core.windows.net/actions-results/156eb5e3-9316-4144-aa45-b01062963416/workflow-job-run-6f2d5b67-27d1-56e0-a369-a1a5524197d4/logs/job/job-logs.txt?rsct=text%2Fplain&se=2026-08-26T18%3A07%3A58Z&sig=cZU4KKa30xzXdKjNVqVlZ%2BGKRzInpts%2BSZHEAlfWe7M%3D&ske=2026-08-26T20%3A42%3A02Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2026-08-26T16%3A42%3A02Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-11-05&sp=r&spr=https&sr=b&st=2026-08-26T17%3A57%3A53Z&sv=2025-11-05)

**Excerpt from the same Log's file:**
```
2026-08-26T17:57:26.5809149Z ##[error***The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2026-08-26T17:57:26.6562056Z ##[debug***Re-evaluate condition on job cancellation for step: 'Run daily upload'.
2026-08-26T17:57:26.6589960Z ##[debug***Skip Re-evaluate condition on runner shutdown.
2026-08-26T17:57:27.0247331Z ##[error***The operation was canceled.
2026-08-26T17:57:27.0261700Z ##[debug***System.OperationCanceledException: The operation was canceled.
2026-08-26T17:57:27.0271161Z ##[debug***   at System.Threading.CancellationToken.ThrowOperationCanceledException()
2026-08-26T17:57:27.0277721Z ##[debug***   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
2026-08-26T17:57:27.0293574Z ##[debug***   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
2026-08-26T17:57:27.0302292Z ##[debug***   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
2026-08-26T17:57:27.0310678Z ##[debug***   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
2026-08-26T17:57:27.0314956Z ##[debug***   at GitHub.Runner.Worker.ActionRunner.RunAsync()
2026-08-26T17:57:27.0319237Z ##[debug***   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2026-08-26T17:57:27.0328714Z ##[debug***Finishing: Run daily upload
2026-08-26T17:57:27.0624271Z ##[debug***Evaluating condition for step: 'Post Set up Python'
2026-08-26T17:57:27.0628952Z ##[debug***Skip evaluate condition on runner shutdown.
2026-08-26T17:57:27.0673043Z ##[debug***Evaluating condition for step: 'Post Checkout repository'
2026-08-26T17:57:27.0677188Z ##[debug***Skip evaluate condition on runner shutdown.
2026-08-26T17:57:27.0883675Z ##[debug***Starting: Complete job
2026-08-26T17:57:27.0929041Z Uploading runner diagnostic logs
2026-08-26T17:57:27.1026740Z ##[debug***Starting diagnostic file upload.
2026-08-26T17:57:27.1039762Z ##[debug***Setting up diagnostic log folders.
2026-08-26T17:57:27.1076034Z ##[debug***Creating diagnostic log files folder.
2026-08-26T17:57:27.1142565Z ##[debug***Copying 1 worker diagnostic logs.
2026-08-26T17:57:27.1222606Z ##[debug***Copying 1 runner diagnostic logs.
2026-08-26T17:57:27.1236372Z ##[debug***Zipping diagnostic files.
2026-08-26T17:57:27.1468893Z ##[debug***Uploading diagnostic metadata file.
2026-08-26T17:57:27.1861226Z ##[debug***Diagnostic file upload complete.
2026-08-26T17:57:27.1888756Z Completed runner diagnostic log upload
2026-08-26T17:57:27.1902350Z Cleaning up orphan processes
2026-08-26T17:57:27.3459783Z ##[debug***Finishing: Complete job
2026-08-26T17:57:27.3513759Z ##[debug***Finishing: upload` 

```
