### ISSUE TITLE
Runners fail to set up job with tar -xzf error 

### ISSUE THREAD

**Issue by gabrielrdrguez** [actions/runner#2824]
**Describe the bug**
actions/checkout is failing with 
```
Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_56b51ce2-efe8-41fe-93a9-50183dbbd11d/18943cb2-ddeb-4981-8a5d-f1684ebdf51d.tar.gz. return code: 2.
```

**To Reproduce**
1. run action with 'actions/checkout@v3'

**Expected behavior**
actions should be complete without any errors

## Runner Version and Platform
Current runner version: '[2](https://github.com/qcx/atlas/actions/runs/6074119855/job/16478002064#step:1:2).[3](https://github.com/qcx/atlas/actions/runs/6074119855/job/16478002064#step:1:3)08.0'
Operating System
  Ubuntu
  22.0[4](https://github.com/qcx/atlas/actions/runs/6074119855/job/16478002064#step:1:4).3
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20230821.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230821.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230821.1
Runner Image Provisioner
  2.0.264.1
## What's not working?
setup up job 

## Job Log Output
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_56b51ce2-efe8-41fe-93a9-50183dbbd11d/18943cb2-ddeb-4981-8a5d-f1684ebdf51d.tar.gz. return code: 2.

**Comment by schibrikov** [comment]
Experiencing the same issue currently. Seems to be the same as https://github.com/actions/runner/issues/1923
So waiting for action from GitHub

**Comment by nicolas2mey** [comment]
same on some repositories on our organization

**Comment by ruiguerrapsyomics** [comment]
Same here... Thanks for raising the issue!

**Comment by TheByronHimes** [comment]
Same with us

**Comment by rajesh094780** [comment]
Same on our side also:)

**Comment by sgonzalez-pluto** [comment]
Same here.

**Comment by kearfy** [comment]
Seems to affect half of the runners, some of them work just fine

**Comment by Danny-Cooke-cCK** [comment]
affecting us too

**Comment by sohail-mp** [comment]
same here

**Comment by rmellis** [comment]
Same here

**Comment by aravindhghosh** [comment]
We have the same issues

**Comment by binarymaster** [comment]
Same problem happening on `ubuntu-latest`, as well as on `macos-latest`: https://github.com/adplug/adplug/actions/runs/6074041728/job/16479049156

```sh
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Error: '/Users/runner/work/_actions/_temp_a814904e-fd90-413c-911f-abb439034704/3499ecb5-0124-4a44-b981-136de143db04.tar.gz' contains '0' directories
```

**Comment by kearfy** [comment]
All my actions seem to be working again!

**Comment by Bilal-Mohiuddin** [comment]
Looks like this has been resolved now
https://www.githubstatus.com/incidents/76xp2jd3px64

**Comment by rajesh094780** [comment]
looks like issued resolved
https://www.githubstatus.com/?subscription_confirmed=true

**Comment by dalkio** [comment]
I still have the issue, it seems to appear randomly across my jobs

**Comment by facundobuitrago** [comment]
same here

**Comment by rajesh094780** [comment]
still same issued

**Comment by scottquested** [comment]
Just this second happened again for us

**Comment by jscant-lunit** [comment]
Happening for us too. It was happening a few hours ago then was fixed then started again.
