### ISSUE TITLE
Unsupported macOS container/docker action error message

### ISSUE THREAD

**Issue by anthonysterling** [actions/runner#715]
**Describe the bug**

When running a workflow on macOS if you use a container/docker action you receive an error message that doesn't describe the fact that container/docker action aren't supported on macOS.

> `Error: Value cannot be null. (Parameter 'container')`

It would be ✨ if this message could be improved.

**To Reproduce**

1. Create a workflow that targets macOS
2. Use a container/docker action
3. See error `Error: Value cannot be null. (Parameter 'container')`

**Expected behavior**

An error message that describes that container/docker action aren't supported on macOS would be nice.

## Runner Version and Platform

Latest/Hosted runner on macOS

## Job Log Output

An example of the error can be seen here https://github.com/automationcloud/autopilot/runs/1143430926?check_suite_focus=true

**Comment by andrevidela** [comment]
Any info on when this will be either fixed/implemented?

**Comment by nikola-jokic** [comment]
This issue has been fixed:
<img width="588" alt="Screenshot 2022-03-07 at 14 44 42" src="https://user-images.githubusercontent.com/97525037/157045966-0633c48d-6f08-4610-86c7-c73339d0ee84.png">

Also, please note that the [documentation](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#introduction) states that you should only run container-based actions on Linux systems. It holds true both for self-hosted and for hosted runners.

**Comment by behrisch** [comment]
Sorry for reviving an old issue but I still see the error message `Value cannot be null. (Parameter 'container')`
when running on the new macos-14 hosed runner.

**Comment by plroebuck** [comment]
Same. I wasted God knows how much time thinking I was doing something wrong trying to get it working on  'macos-13', 'macos-14', and 'macos-15'. Not a word that it only works on certain platforms. I just wound up installing it via a different Docker container instead...

**Comment by joeycumines** [comment]
Yeah, this does appear to have regressed. I've opened a new issue, since I can't reopen this one 🤷.
