### ISSUE TITLE
unable to inject shell to composite action

### ISSUE THREAD

**Issue by igagis** [actions/runner#835]
**Describe the bug**
Unable to pass the shell via input parameter to the composite action.

**To Reproduce**
1. create following composite action:
````
name: 'test actions'
description: 'test action description'
inputs:
  shell:
    description: 'shell to use'
    required: false
    default: bash
runs:
  using: "composite"
  steps:
    - name:
      run: echo "bla bla bla"
      shell: ${{ inputs.shell}}
````
2. use the action in some workflow
3. Job fails on the 'Set up job' phase, printing the following errors:
````
Current runner version: '2.274.2'
Operating System
Virtual Environment
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'msys2/setup-msys2@v2'
Download action repository 'actions/checkout@main'
Download action repository 'myci-actions/add-pacman-repo@master'
Error: myci-actions\add-pacman-repo\master\action.yml (Line: 25, Col: 14):
Error: myci-actions\add-pacman-repo\master\action.yml (Line: 25, Col: 14): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.shell
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. myci-actions\add-pacman-repo\master\action.yml (Line: 25, Col: 14): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.shell
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String f[...]
Error: Fail to load myci-actions\add-pacman-repo\master\action.yml
````

where `(Line: 25, Col: 14)` corresponds to the last line of the action from step 1. I.e. `shell: ${{ inputs.shell}}`

**Expected behavior**
The action works fine and uses the shell passed in as input argument to the action.

## Runner Version and Platform
`windows-latest`

**Comment by chenghuang-mdsol** [comment]
Yea. this is annoying, please fix this.

**Comment by marten-seemann** [comment]
Now that GitHub Actions supports `if`s in steps, this can be simplified a bit:
```yml
    - name: create bash-or-msys2 (for bash)
      shell: bash
      if: inputs.shell == 'bash'
      run: sudo ln -sf $(which bash) /usr/local/bin/bash-or-msys2
    - name: create bash-or-msys2 (for msys2)
      shell: bash
      if: inputs.shell == 'msys2 {0}'
      run: |
        if [[ ! -f "D:/a/_temp/setup-msys2/bash-or-msys2.cmd" ]]; then
          powershell New-Item -ItemType SymbolicLink -Path "D:/a/_temp/setup-msys2/bash-or-msys2.cmd" -Target "D:/a/_temp/setup-msys2/msys2.cmd"
        fi
```

**Comment by tfgstudios** [comment]
1 year?

**Comment by igagis** [comment]
@tfgstudios this is how software is developed nowadays...

**Comment by reuben** [comment]
Weirdly this feature is explicitly documented in an ADR as if it should work seamlessly: https://github.com/actions/runner/blob/e7d74da1600b1aa8ac8db18cc4c76ef44a82e689/docs/adrs/0549-composite-run-steps.md#shell-and-working-directory

**Comment by reuben** [comment]
@ethanchewy since you wrote the docs above maybe you can comment on the status here?

**Comment by nikola-jokic** [comment]
Hey everyone, we are reproducing this issue and we will notify you as soon as it is fixed 😊

**Comment by ironstas1k** [comment]
We are still experiencing this issue using **ubuntu-latest** runners.

```
[Invalid workflow file: .github/workflows/workflow_test.yml#L20](https://github.com/talon-sec/tcore/actions/runs/2992523842/workflow)
The workflow is not valid. .github/workflows/workflow_test.yml (Line: 20, Col: 16): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.shell .github/workflows/workflow_test.yml (Line: 24, Col: 16): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.shell
```

Workflow
```
name: Workflow Tests

on:
  workflow_dispatch:
    inputs:
      shell:
        description: 'shell to use'
        required: false
        default: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Verify parameters
        run: echo "cond step"
        shell: ${{ inputs.shell }}
```

**Comment by AvivPeledTalon** [comment]
> We are still experiencing this issue using **ubuntu-latest** runners.
> 
> ```
> The workflow is not valid. .github/workflows/workflow_test.yml (Line: 20, Col: 16): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.shell .github/workflows/workflow_test.yml (Line: 24, Col: 16): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.shell
> ```
> 
> Workflow
> 
> ```
> name: Workflow Tests
> 
> on:
>   workflow_dispatch:
>     inputs:
>       shell:
>         description: 'shell to use'
>         required: false
>         default: bash
> jobs:
>   test:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Verify parameters
>         run: echo "cond step"
>         shell: ${{ inputs.shell }}
> ```

Also experiencing this. 
Did your fix only affect composite actions? It seems like it doesn't affect run steps (they still don't recognize the inputs context)
